spring:
  application:
    name: Admin
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: donation
    password: xiaomao2000
server:
  port: 8300
